### ISSUE TITLE
Metalink tests reports deprecation message

### ISSUE THREAD

**Issue by sidcha** [vmware/tdnf#172] opened 2020-09-11 12:55 UTC
When running make tests, I get the following deprecation message.

```
tests/test_metalink.py:51
  /root/tdnf/pytests/tests/test_metalink.py:51: DeprecationWarning: invalid escape sequence \
    utils.run([ 'sed', '-i', '-e' ,'/<verification>/a \    <hash type="md5">' + md5sum + '</hash>', photon_metalink ])

tests/test_metalink.py:62
  /root/tdnf/pytests/tests/test_metalink.py:62: DeprecationWarning: invalid escape sequence \
    utils.run([ 'sed', '-i', '-e' ,'/<verification>/a \    <hash type="sha1">' + sha1sum + '</hash>', photon_metalink ])

tests/test_metalink.py:72
  /root/tdnf/pytests/tests/test_metalink.py:72: DeprecationWarning: invalid escape sequence \
    utils.run([ 'sed', '-i', '-e' ,'/<verification>/a \    <hash type="sha256">' + sha256sum + '</hash>', photon_metalink ])

tests/test_metalink.py:79
  /root/tdnf/pytests/tests/test_metalink.py:79: DeprecationWarning: invalid escape sequence \
    utils.run([ 'sed', '-i', '-e' ,'/<verification>/a \    <hash type="md5">' + md5sum + '</hash>', photon_metalink ])

tests/test_metalink.py:84
  /root/tdnf/pytests/tests/test_metalink.py:84: DeprecationWarning: invalid escape sequence \
    utils.run([ 'sed', '-i', '-e' ,'/<verification>/a \    <hash type="sha1">' + sha1sum + '</hash>', photon_metalink ])

tests/test_metalink.py:89
  /root/tdnf/pytests/tests/test_metalink.py:89: DeprecationWarning: invalid escape sequence \
    utils.run([ 'sed', '-i', '-e' ,'/<verification>/a \    <hash type="sha256">' + sha256sum + '</hash>', photon_metalink ])

tests/test_metalink.py:94
  /root/tdnf/pytests/tests/test_metalink.py:94: DeprecationWarning: invalid escape sequence \
    utils.run([ 'sed', '-i', '-e' ,'/<verification>/a \    <hash type="sha256">' + sha256sum + '</hash>', photon_metalink ])

tests/test_metalink.py:99
  /root/tdnf/pytests/tests/test_metalink.py:99: DeprecationWarning: invalid escape sequence \
    utils.run([ 'sed', '-i', '-e' ,'/<verification>/a \    <hash type="sha1">' + sha1sum + '</hash>', photon_metalink ])
```

**Comment by sidcha** [comment] 2020-09-11 12:55
^^^ @tapakund

**Comment by tapakund** [comment] 2020-09-14 12:08
https://github.com/vmware/tdnf/pull/167 fixes this issue.

**Comment by tapakund** [comment] 2020-09-14 12:09
This is dupe of https://github.com/vmware/tdnf/issues/150

**Closed as completed** 2020-09-14 12:18 UTC
